### ISSUE TITLE
Feels like there's something missing here... ;-)

### ISSUE THREAD

**Issue by nelsonic** [hdrdavies/Resume#5]
@hdrdavies it _feels_ like there's something *missing* here...
https://github.com/hdrdavies/Resume/tree/9c47011f3a3a2f08b28598d4e80b2821cee021c6
but I can't quite put my finger on what it is...
you have learned _so_ much in the past 18 months ...
almost feels like a _waste_ to not get "***inspiration***" from one of your peers:
+ @Neats29 (F&C 4): https://github.com/Neats29/CV
and/or
+ @heron2014 (F&C 5): https://github.com/heron2014/CV
😉 
(_hope you're well Huw! miss you man!_)

**Comment by hdrdavies** [comment]
Haha you're right @nelsonic. Though I'm not sure I want to attract unwanted attention 😉 (at the moment anyway)  

You can always look in the git history to see my older versions 😝 

I'm coming into FAC later today so hopefully see you there dude 🎉

**Comment by nelsonic** [comment]
LoL! "_unwanted attention..._" 🤣 
Recruiters gonna recruit... 😜 
Great to catch up with you, sounds like you're having a _blast_ at Zuhlke! 🚀 
Love you! See you soon! ❤️  ✅
